### ISSUE TITLE
Weird Puma Error

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/your-own-js-and-css-in-rails#12]
I received a weird puma error after getting rid of the Gemfile.lock, and running `bundle install`

`LoadError:
       Capybara is unable to load `puma` for its server, please add `puma` to your project or specify a different server via something like `Capybara.server = :webrick`.`

Not sure what it is, but I am almost certain I have completed what the specs are testing for. Any feedback would be much appreciated!

**Comment by gnappo1** [comment]
Adding: gem 'puma' to Gemfile and running 'bundle install' fixed the issue in my case.
Specifying a version for puma was not necessary.
We also settled to Rails 5.2 in the various attempts to solve the issue, just as general info.

**Comment by dwyn** [comment]
In hindsight, I have no idea why I didn't try that - The error explicitly suggests it! Thanks Matteo!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
