### ISSUE TITLE
PhantomJS error

### ISSUE THREAD

**Issue by mstmari** [learn-co-curriculum/your-own-js-and-css-in-rails#13]
I encountered the phantomJS error, after a bit of searching and head scratching I saw the note about this error at the bottom of the lab readme to run `brew install phantomjs` upon running that line in the terminal I was vexed to encounter the same issue again. Upon reading through the error in the terminal -  the update is: `brew cask install phantomjs` (the _cask_ had been left out)

Just a heads up - you might want to update.  
sorry for the long explanation.

**Comment by atxrenegade** [comment]
// ♥brew install phantomjs
Error: No available formula with the name "phantomjs"
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install phantomjs

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
