### ISSUE TITLE
phantomjs has been officially discontinued upstream. It may stop working correctly (or at all) in recent versions of macOS.

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/your-own-js-and-css-in-rails#14]
// ♥brew cask install phantomjs
==> Caveats
phantomjs has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.

**Comment by drakeltheryuujin** [comment]
Hi @atxrenegade,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
