### ISSUE TITLE
Tests dont pass using let to declare variables instead of var

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/your-own-js-and-css-in-rails#15]
Using let results in the following error: 
 Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about
these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (s
ee documentation for details).

       ReferenceError: Can't find variable: hideWhenClicked

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
