### ISSUE TITLE
Duplication in the text of this lab

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/your-own-js-and-css-in-rails#16]
The text was copied and pasted twice in this lab. It should end after the first Phantom JS Errors section.

Objectives
Write your own CSS and integrate it into the asset pipeline and use it in views.
Write your own JS and integrate it into the asset pipeline and use it in views.
Objectives
Located in this repository is a simple Rails application. Your goal is to create your own JS and CSS and include it into the application. You can run the Capybara spec when you are finished to test your solution.

First add the following JS:

In /app/assets/javascripts/ create the file hide.js
Create the function hideWhenClicked that hides the element that was clicked.
Make sure to bind to #hide_this
Add hide.js to your JS manifest.
Note: If declaring any variables in your JavaScript file, use var instead of let or const or else Capybara will throw this error:

Capybara::Poltergeist::JavascriptError:
One or more errors were raised in the Javascript code on the page. If you don't care about
these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (s
ee documentation for details).
Next add the following CSS:

In /app/assets/stylesheets/ create the file links.css
Create a CSS class called .error that changes the color of the text to red. Add this CSS class to the link on the root page.
Create another CSS class called .cool-background that makes the background grey. Add this CSS class to the <body> tag on the application layout.
Add links.css to your CSS manifest.
PhantomJS Errors
If you receive this error:

Could not find an executable ["phantomjs"] on your path.

Install it with: `# Your Own Js And Css In Rails

Objectives
Write your own CSS and integrate it into the asset pipeline and use it in views.
Write your own JS and integrate it into the asset pipeline and use it in views.
Objectives
Located in this repository is a simple Rails application. Your goal is to create your own JS and CSS and include it into the application. You can run the Capybara spec when you are finished to test your solution.

First add the following JS:

In /app/assets/javascripts/ create the file hide.js
Create the function hideWhenClicked that hides the element that was clicked.
Make sure to bind to #hide_this
Add hide.js to your JS manifest.
Next add the following CSS:

In /app/assets/stylesheets/ create the file links.css
Create a CSS class called .error that changes the color of the text to red. Add this CSS class to the link on the root page.
Create another CSS class called .cool-background that makes the background grey. Add this CSS class to the <body> tag on the application layout.
Add links.css to your CSS manifest.
PhantomJS Errors
If you receive this error:

Could not find an executable ["phantomjs"] on your path.

Install it with: brew cask install phantomjs

**Comment by maxwellbenton** [comment]
Hi @A-Glazer,

Thank you for this feedback. We've removed the duplicate text in this lesson, which should resolve this issue for future students. We apologize for any frustration this may have caused, but appreciate you taking the time to let us know.

Thank you for contributing to a Learn lesson!
