### ISSUE TITLE
`brew cask install phantomjs` doesn't work on windows

### ISSUE THREAD

**Issue by A-Glazer** [learn-co-curriculum/your-own-js-and-css-in-rails#18]
The instructions say to install phantomjs with `brew cask install phantomjs`, however, that does not work on Windows. To install it, add the gem ‘phantomjs’, :require => ‘phantomjs/poltergeist’ to your gemfile. Delete gemfile.lock first and then bundle install.

**Comment by maxwellbenton** [comment]
Hi @A-Glazer,

Thank you for this feedback. We've added an additional instruction specific to installing phantomjs on the Windows Subsystem for Linux, which should resolve this issue for future students. We apologize for any frustration this may have caused, but appreciate you taking the time to let us know.

Thank you for contributing to a Learn lesson!
