### ISSUE TITLE
Lab does not run on Learn IDE

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/your-own-js-and-css-in-rails#3]
This lab needs firefox to run on the Learn IDE. 

@cernanb found a fix for this though here: learn.co/handraise_questions/28628

@mendelB I think this is in your section now? Feel free to bounce it if I'm wrong.

cc @AnnJohn @PeterBell

**Comment by bhollan** [comment]
Had a student run into a similar issue on this lab today (Selenium::Webdriver).  Support docs said to check FireFox, we did, didn't fix it.

Tried the workaround described in the chat link above and it worked.
I made a [PR for the support docs](https://github.com/flatiron-labs/learn-support/pull/145).

CC: @aturkewi

**Comment by aturkewi** [comment]
@bhollan can you PR this lab when you get a chance to add the fix?
