### ISSUE TITLE
Could not find an executable ["phantomjs"] on your path.

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/your-own-js-and-css-in-rails#7]
Some tests failed with error:

`Cliver::Dependency::NotFound:
Could not find an executable ["phantomjs"] on your path.`

Adding `gem 'phantomjs', :require => 'phantomjs/poltergeist'` fixed this issue

**Comment by FreeBreadsticks** [comment]
Thank you, I was getting that same error and this worked for me as well!

**Comment by CLackrone** [comment]
This worked for me too.

**Comment by hansenjl** [comment]
If you are using a local environment  and on a mac, try running `brew install phantomjs` in the terminal instead of adding it to the gemfile.

**Comment by sgharms** [comment]
Thanks everyone, we're going to integrate this into master.

**Comment by ortonomy** [comment]
This doesn't prevent missing [phantomjs], only poltergeist, on MacOS. ``brew install ...`` is more reliable.

**Comment by nmlstyl** [comment]
anyone know if i should be using phantomjs 2.1.1.0

**Comment by amuntasim** [comment]
`Mac Os El Capitan `

`npm install -g phantomjs`
