### ISSUE TITLE
Needed to add gem to gemfile to get the tests to run properly

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/your-own-js-and-css-in-rails#9]
I was getting this error:

> `Cliver::Dependency::NotFound:
            Could not find an executable ["phantomjs"] on your path.`

Did a bit of research and added:

`gem 'phantomjs', :require => 'phantomjs/poltergeist'`

Now, tests are running fine.

**Comment by sgharms** [comment]
Thanks for this input. We've approached it differently, but good thinking.

💙
